### ISSUE TITLE
color scheme

### ISSUE THREAD

**Issue by nosrednaharas** [sirjessthebrave/sirjessthebrave.github.io#9]
what do you think of this color scheme?
http://nycpalette.tumblr.com/post/110078961326/south-street-seaport-inspiration  I thought it kind of went with the RepEquity logo. Also, when in doubt, I do red white and blue. This is DC...

**Comment by sirjessthebrave** [comment]
I like it!  My CEO will LOVE it!

**Comment by nosrednaharas** [comment]
Awesome! Want to do another weekend coffee and code? 

I need coding help on my work map - it has become slightly more pressing.

**Comment by sirjessthebrave** [comment]
Let me check my calendar but probably!  We should think of a place with better wifi maybe...let's talk @guild tonight!

**Comment by sirjessthebrave** [comment]
Closing this as we never got to this!  But next time!
